<?php
namespace App\Console\Command;

use App\Environment;
use AzuraCast\Api\Client;
use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Psr7\Uri;
use Symfony\Component\Console\Question;
use Symfony\Component\Console\Style\SymfonyStyle;

class SetupCommand extends CommandAbstract
{
    public function __invoke(
        SymfonyStyle $io,
        GuzzleClient $httpClient,
        Client $api,
        Environment $environment
    ) {
        $io->title('AzuraRelay Setup');
        $io->writeln('Welcome to AzuraRelay! Provide the following items to finish setup.');

        //
        // Parent installation URL
        //
        $io->section('AzuraCast Installation URL');
        $io->writeln('AzuraRelay has to connect to a "parent" AzuraCast instance to relay its broadcast(s).');
        $io->writeln('Provide the base URL of that installation (including "http://" or "https://") to continue.');

        $question = new Question\Question('AzuraCast Installation URL', getenv('AZURACAST_BASE_URL'));
        $question->setMaxAttempts(10);
        $question->setValidator(function($value) use ($httpClient) {
            try {
                $api = Client::create($value, null, $httpClient);
                $np = $api->nowPlaying();
            } catch(\Exception $e) {
                throw new \RuntimeException(sprintf('Could not connect to AzuraCast instance at %s: %s', $value, $e->getMessage().' '.$e->getFile().' L'.$e->getLine().': '.$e->getTraceAsString()));
            }

            return $value;
        });

        $baseUrl = $io->askQuestion($question);

        if (empty($baseUrl)) {
            $io->error('You must provide an AzuraCast Base URL to continue.');
            return 1;
        }

        //
        // API Key
        //
        $apiKeyUrl = (string)(new Uri($baseUrl))->withPath('/api_keys');

        $io->section('AzuraCast API Key');
        $io->writeln('You must provide an API key for an authorized account on this installation.');
        $io->writeln('You can generate a new API key at:');
        $io->listing([$apiKeyUrl]);

        $question = new Question\Question('AzuraCast API Key', getenv('AZURACAST_API_KEY'));
        $question->setMaxAttempts(10);
        $question->setValidator(function($value) use ($baseUrl, $httpClient) {
            $api = Client::create($baseUrl, $value, $httpClient);
            $relays = $api->admin()->relays()->list();

            if (0 === count($relays)) {
                throw new \RuntimeException('No relayable streams were found on the remote server. Make sure your account has permission to "Manage Broadcasting" for the station you want to relay.');
            }

            return $value;
        });

        $apiKey = $io->askQuestion($question);

        if (empty($apiKey)) {
            $io->error('You must provide an API key to continue.');
            return 1;
        }

        //
        // Relay Name
        //

        $io->section('About This Relay');
        $io->writeln('You can now provide some details about this relay.');
        $io->writeln('These details will be reported back to the parent AzuraCast instance and');
        $io->writeln('displayed to listeners if this relay is public.');

        $question = new Question\Question('Relay Display Name', getenv('AZURARELAY_NAME') ?? 'Relay');
        $relayName = $io->askQuestion($question);

        //
        // Relay Base URL
        //

        $publicIp = @file_get_contents('http://ipecho.net/plain');

        $question = new Question\Question('Relay Base URL', getenv('AZURARELAY_BASE_URL') ?? $publicIp);
        $relayBaseUrl = $io->askQuestion($question);

        //
        // Relay is Public
        //

        $question = new Question\ConfirmationQuestion('Show This Relay to AzuraCast Listeners?', getenv('AZURARELAY_IS_PUBLIC') ?? true);
        $relayIsPublic = $io->askQuestion($question);

        $io->section('Generating configuration file...');

        $envFile = [
            '# This file was automatically generated by AzuraRelay. You can modify it if needed.',
            '',
            '# The base URL for the parent AzuraCast instance.',
            'AZURACAST_BASE_URL='.$baseUrl,
            '',
            '# The API key for an authorized user on the parent AzuraCast instance.',
            'AZURACAST_API_KEY='.$apiKey,
            '',
            '# The display name of this relay.',
            'AZURARELAY_NAME='.$relayName,
            '',
            '# The base URL of this relay.',
            'AZURARELAY_BASE_URL='.$relayBaseUrl,
            '',
            '# Whether this relay is shown to listeners on the parent AzuraCast instance.',
            'AZURARELAY_IS_PUBLIC='.($relayIsPublic ? 'true' : 'false'),
            '',
        ];

        $temp_path = $environment->getTempDirectory().'/azurarelay.env';
        file_put_contents($temp_path, implode("\n", $envFile));

        $io->note($envFile);

        $io->success('Setup is complete!');
        return 0;
    }
}
