services:
  relay:
    image: azuracast/azurarelay:latest
    build:
      context: .
    environment:
      APPLICATION_ENV: testing
    volumes:
      - tmp_data:/var/azurarelay/www_tmp
      - station_data:/var/azurarelay/stations

volumes:
  station_data: {}
  tmp_data: {}
